version: "3"
services:
  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_proto
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql