server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.146.128:3306/demo?useSSL=false&&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 192.168.146.128
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
#  jackson:
#    default-property-inclusion: non_null # JSON处理时忽略非空字段
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 全局日期格式
    time-zone: GMT+8                  # 时区设置
    serialization:
      write-dates-as-timestamps: false # 禁用时间戳
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

canal:
  server: 127.0.0.1:11111
  destination: example




rocketmq:
  name-server: 127.0.0.1:9876 # name server 地址
  producer:
    group: xiaohashu_group
    send-message-timeout: 3000 # 消息发送超时时间，默认 3s
    retry-times-when-send-failed: 3 # 同步发送消息失败后，重试的次数
    retry-times-when-send-async-failed: 3 # 异步发送消息失败后，重试的次数
    max-message-size: 4096 # 消息最大大小（单位：字节）
  consumer:
    group: xiaohashu_group
    pull-batch-size: 5 # 每次拉取的最大消息数

jwt:
  #    # 设置jwt签名加密时使用的秘钥
  #    admin-secret-key: itcast
  #    # 设置jwt过期时间
  #    admin-ttl: 7200000
  #    # 设置前端传递过来的令牌名称
  #    admin-token-name: token
  user-secret-key: ThisIsA32BytesLongSecretKeyForHS256
  user-ttl: 7200000
  user-token-name: authorization